services:
  - type: web
    name: gdms-taiwan
    env: python
    region: singapore
    plan: free
    buildCommand: pip install --force-reinstall --no-cache-dir -r requirements.txt
    startCommand: python app.py
